### PR TITLE
Add module for multi-region buckets (telia-oss)

### PR DESCRIPTION
**Pull request by itsdalmo**
The idea here is that we should be able to have Travis upload `lambda.zip`, and then have it replicated to all regions, and then we can write `s3_bucket = "telia-oss-${data.aws_caller_id.region_name}"` in our Lambda modules and have it work magically across all regions 🐺

### CODE REVIEW

**Review by colincoleman — APPROVED** [review]
LGTM

**Comment by itsdalmo** [comment]
Travis builds are being rejected with "abuse detected"; I have emailed support and will hopefully get it resolved so we can have green commits before we merge.

**Comment by mikael-lindstrom** [comment]
Where did you see that notification from Travis?

**Comment by itsdalmo** [comment]
If you go to the travis page for this repo, and then select the 'requests' page.

**Comment by itsdalmo** [comment]
@mikael-lindstrom - Travis is fixed. Thoughts on the PR?

**Review by mikael-lindstrom — APPROVED** [review]
LGTM, question is if we want to have another module to do replication within the same region or if this should be expanded to just take a list of buckets regardless of region. But we can think about that later so lets merge this 👍

**Pull request merged**
